import '../styles/globals.css';
import '../styles/Team.css'
import '../styles/SelectTeam.css'

import { Inter } from 'next/font/google'
import Providers from './redux/provider';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Futbol APP</title>
      </Head>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html >
  )
}
