import '../styles/globals.css';
import '../styles/Team.css'
import '../styles/SelectTeam.css'
import { Analytics } from "@vercel/analytics/react"
import { Inter } from 'next/font/google'
import Providers from './redux/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FUTBOL APP',
  description: 'Generated by Sebastián Delescabe',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Analytics/>
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html >
  )
}
